### ISSUE TITLE
Code not working for honeybee with Generate Colors and Display.ByGeometryColor(node)

### ISSUE THREAD

**Issue by yenhsuanho** [ladybug-analysis-tools/honeybee-plus#23]
hi all,
I followed the steps of tutorial video,
(SFDUG July 2016: LadyBug | A Parametric Environmental Plugin for Dynamo)
but now I am getting the error below in Generate Colors and Display.ByGeometryColor(node).

(As shown in the attached file)
# [Generate Colors]

ERROR: 
interation over non-sequence of type StackValue.
If you think this is a bug submit an issue on github.
https://github.com/ladybug-analysis-tools/honeybeex/issues
# [Display.ByGeometryColor]

Warning: One or more of the input types are not matching.
Couldn't find a version of ByGeometryColor that takes arguments of type (__array,string)

How can I achieve this? Can you teach me how to do it? 
Thanks!

![analysis](https://cloud.githubusercontent.com/assets/22050885/18315739/a30e7806-754a-11e6-8fd4-398bd4347abd.png)
![step2](https://cloud.githubusercontent.com/assets/22050885/18315742/a68dd3fa-754a-11e6-9216-0d8ef8c4d5f9.jpg)

**Comment by mostaphaRoudsari** [comment]
I replied to this under honeybee repository: https://github.com/mostaphaRoudsari/Honeybee/issues/559
