### ISSUE TITLE
Code not working on Revit 2017 / Dynamo 1.2

### ISSUE THREAD

**Issue by ejs-ejs** [ladybug-analysis-tools/honeybee-plus#25]
Hi,

When running '03_SunlighthoursAnalysis.dyn' from Dynamo on Revit, the 'Sunpath' module spills an error:
It refers "%Profile%\Appdata\Roaming\\Dynamo\Dynamo Core\1.2\", while "%Profile%\Appdata\Roaming\Dynamo\Dynamo Revit\1.2\" is available only.

Seems the code is somehow not clean here:
_dynamoPaths = (_dynamoPath.replace('Dynamo Core', 'Dynamo Revit'),
                    _dynamoPath.replace('Dynamo Revit', 'Dynamo Core'))
    _settingsFilename = 'DynamoSettings.xml'

**Comment by mostaphaRoudsari** [comment]
@ejs-ejs what's the error message? The code that you pasted is actually trying to avoid this issue by checking for Honeybee first under `Dynamo Revit` folder and then under `Dynamo Core`. Do you have Honeybee installed correctly?

**Comment by ejs-ejs** [comment]
Sorry, i'm unable to copya the error message, because of the watches in Dynamo.

I've installed Honeybee and Ladybug via Dynamo package manager.
The sketch runs if i dumb-copy "Dynamo Revit" to "Dynamo Core" folder.

**Comment by mostaphaRoudsari** [comment]
Hi @ejs-ejs. Thank you for the quick reply. Even if you can send me a screen capture that would be helpful. I will also try to recreate the issue on my system.

**Comment by ejs-ejs** [comment]
Hi,
this is multi-part screen capture from Dynamo ;)
![paveikslas](https://cloud.githubusercontent.com/assets/14044646/20531320/1519fdec-b0df-11e6-8635-b1c019e7ea71.png)
![paveikslas](https://cloud.githubusercontent.com/assets/14044646/20531365/33b46440-b0df-11e6-8a81-8ce8865982a4.png)
![paveikslas](https://cloud.githubusercontent.com/assets/14044646/20531401/4f7ce08a-b0df-11e6-9dde-28fedf5d4751.png)

Please note the "Dynamo Core" is referenced twice in the string: before the column and after.
Is there any way to see these messages in plaintext?

**Comment by mostaphaRoudsari** [comment]
Thanks! I'm checking the issue now.

**Comment by mostaphaRoudsari** [comment]
I uninstalled Ladybug and Honeybee and installed ladybug from package manager and then tried to recreate the issue but everything works fine. You can write the content of the watch component to a text file like this.

![image](https://cloud.githubusercontent.com/assets/2915573/20534314/cf340744-b0ae-11e6-8ae8-65b6133f7e8f.png)

I think the best way to understand the issue is to run the code that tries to get the path separately and see what does it return. Can you copy this code in a python node and let me know what are the outputs? This is something easy to fix if we can figure out why it's happening in the first place.

```python
"""Find packages from Dynamo folder and prepare the code."""
import clr
from System import AppDomain, Environment, IO

def tryGetPluginPath(plugin):
    """Try to get path to plugin folder."""
    clr.AddReference('ProtoGeometry')
    _loc = tuple(a.Location
                 for a in AppDomain.CurrentDomain.GetAssemblies()
                 if 'ProtoGeometry' in a.FullName)

    try:
        _ver = float(_loc[0].split('\\')[-2])
    except:
        _ver = float(_loc[0].split('\\')[-2].split(' ')[-1])

    assert _ver >= 1.2, 'You need Dynamo 1.2 or higher to use this plugin!'

    _appdata = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)
    _dynamoPath = ('\\').join(_loc[0].split('\\')[-4:-1])
    # if the assembly is cached put Revit folder first, and then try to load it from core
    return (_loc[0], _dynamoPath, _dynamoPath.replace('Dynamo Core', 'Dynamo Revit'),
                    _dynamoPath.replace('Dynamo Revit', 'Dynamo Core'))

OUT = tryGetPluginPath("Ladybug")
```

This is what I get from running the script:
```
C:\Program Files\Dynamo\Dynamo Core\1.2\ProtoGeometry.dll
Dynamo\Dynamo Core\1.2
Dynamo\Dynamo Revit\1.2
Dynamo\Dynamo Core\1.2
```

**Comment by ejs-ejs** [comment]
Confirm 
C:\Program Files\Dynamo\Dynamo Core\1.2\ProtoGeometry.dll
Dynamo\Dynamo Core\1.2
Dynamo\Dynamo Revit\1.2
Dynamo\Dynamo Core\1.2

**Comment by Dheb19** [comment]
I uninstalled and re-installed the Ladybug and Honeybee packages, and ran the script above. I get the same output as yours but still the same error when trying to run Ladybug nodes.
The screen shot is trying to get an .epw file saved on my desktop.
![ladybug errno 2](https://cloud.githubusercontent.com/assets/23659947/20535150/28b01d16-b0ba-11e6-87ed-c216a5bcb592.jpg)

**Comment by mostaphaRoudsari** [comment]
Thank you both. We are very close to get to the bottom of this.

There are two possibilities:
1. The Path.Combine fails to generate the right path that we will know once you run the code below.
2. There is no DynamoSettings.xml file in your installation which is quite strange but possible.

Can you run the code below and see if it outputs these two paths?
C:\Users\`your usename`\AppData\Roaming\Dynamo\Dynamo Revit\1.2\DynamoSettings.xml
C:\Users\`your usename`\AppData\Roaming\Dynamo\Dynamo Core\1.2\DynamoSettings.xml

and then check the folders and see if the xml file exists?

```python
"""Find packages from Dynamo folder and prepare the code."""
import clr
from System import AppDomain, Environment, IO

def tryGetPluginPath(plugin):
    """Try to get path to plugin folder."""
    clr.AddReference('ProtoGeometry')
    _loc = tuple(a.Location
                 for a in AppDomain.CurrentDomain.GetAssemblies()
                 if 'ProtoGeometry' in a.FullName)

    try:
        _ver = float(_loc[0].split('\\')[-2])
    except:
        _ver = float(_loc[0].split('\\')[-2].split(' ')[-1])

    assert _ver >= 1.2, 'You need Dynamo 1.2 or higher to use this plugin!'

    _appdata = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)
    _dynamoPath = ('\\').join(_loc[0].split('\\')[-4:-1])
    # if the assembly is cached put Revit folder first, and then try to load it from core
    _dynamoPaths = (_dynamoPath.replace('Dynamo Core', 'Dynamo Revit'),
                    _dynamoPath.replace('Dynamo Revit', 'Dynamo Core'))
    _settingsFilename = 'DynamoSettings.xml'
    
    return [IO.Path.Combine(_appdata, path, _settingsFilename) for path in _dynamoPaths]
        

OUT = tryGetPluginPath("Ladybug")
```

**Comment by ejs-ejs** [comment]
BTW: DynamoSettings.XML contains:
`<CustomPackageFolders>
    <string>C:\Users\ejs.ARCHES\AppData\Roaming\Dynamo\Dynamo Revit\1.2</string>
  </CustomPackageFolders>`

**Comment by ejs-ejs** [comment]
C:\Users\ejs.ARCHES\AppData\Roaming\Dynamo\Dynamo Revit\1.2\DynamoSettings.xml
C:\Users\ejs.ARCHES\AppData\Roaming\Dynamo\Dynamo Core\1.2\DynamoSettings.xml

There should be no second one i suppose, if Dynamo is only executed from Revit?

**Comment by Dheb19** [comment]
This is what I get when I run the script, however when I go to the Dynamo Folder the "Dynamo Core" is not there.
![dynamo root](https://cloud.githubusercontent.com/assets/23659947/20536529/d2884106-b0bf-11e6-860a-57d54d4742b8.jpg)


C:\Users\denis_h\AppData\Roaming\Dynamo\Dynamo Revit\1.2\DynamoSettings.xml
C:\Users\denis_h\AppData\Roaming\Dynamo\Dynamo Core\1.2\DynamoSettings.xml

**Comment by mostaphaRoudsari** [comment]
Very helpful! It should not check the second path if the packages are available in the first one. Let me check and get back to you soon.

**Comment by mostaphaRoudsari** [comment]
I pushed new versions for both Ladybug and Honeybee to the package manager that should address this issue. Thank you for reporting and your help to get it fixed!

**Comment by Dheb19** [comment]
Thank you! Great work.

**Comment by JoshuaC-STN** [comment]
I still get this Error. I don't think this has been resolved.
