### ISSUE TITLE
Installation issue, files self-deleted

### ISSUE THREAD

**Issue by DambronOlivier** [ladybug-analysis-tools/honeybee-plus#27]
@mostaphaRoudsari 

1 ) After adding 2 folder paths to the GrasshopperDevelopperSettings:

C:\Users\OlivierDambron\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee_grasshopper\
and
C:\Users\OlivierDambron\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\honeybee-plus\honeybee-plus-master\plugin\grasshopper\src\

2 ) In an example file, I run a python component:
>>import honeybee
>>from honeybee.hbsurface import HBSurface

3 ) Enable/Disable the red components.

4 ) Find the writeFolder of the project and right click/ untick "read-only".

It is then possible to use the samplefiles. 

Somehow, when rhino is closed and re-opened or computer restarted, the honeybee plus bar in GH disappears. I have to run the installer and update to restore.

Any thoughts on this?

**Comment by mostaphaRoudsari** [comment]
Hi @DambronOlivier, Do you use Honeybee's (not honeybee[+]) update component? Unless you're using the most recent version of honeybee that will remove any userobject that starts with "Honeybee" including HoneybeePlus components. Is it possible to update honeybee for Grasshopper?

**Comment by DambronOlivier** [comment]
Hi @mostaphaRoudsari , I have updated successfully through Honeybee[+] component. 
I must have had conflicting folders when importing Honeybee and Honeybee[+]. All is good, thanks.

**Comment by mostaphaRoudsari** [comment]
This is fixed both for the update and the import issue.
