### ISSUE TITLE
Radiance Opaque material

### ISSUE THREAD

**Issue by andrewkukla** [ladybug-analysis-tools/honeybee-plus#28]
Hi,

I was wondering whether is is possible to define the properties of the opaque Honeybee surfaces?
Does anyone know what are the default values for floors, walls and roofs?
Honeybee surface seems to need a Radiance material. Is using glass with transmittance=0.0 for opaque surfaces allowed?
![image](https://cloud.githubusercontent.com/assets/24529228/21401118/f2cb7328-c7aa-11e6-82c8-7910845531e8.png)

**Comment by sariths** [comment]
Hi @andrewkukla , assuming that you are are working on a Daylighting simulation, you should use the plastic material to define an opaque surface. Glass with zero transmittance will absorb all the energy that is incident on it.

**Comment by andrewkukla** [comment]
There isn't such node in Honeybee. Does any one know whether this and other day lighting functionality is coming in the next version?

**Comment by mostaphaRoudsari** [comment]
Hi @andrewkukla,

Sorry for the late reply. We don't have a node currently that exposes the opaque materials but you can create your own by using the API. Copy these lines in a Python node with two inputs. The first input is the name and the second is the reflectivity of the surface. Also change %USERNAME% in line 3 to your username.

We will add a node for this in the next release.

```python
import sys
# replace %USERNAME% with your username
sys.path.append(r'C:\Users\%USERNAME%\AppData\Roaming\Dynamo\Dynamo Revit\1.2\packages\Honeybee\extra')
sys.path.append(r'C:\Program Files (x86)\IronPython 2.7\Lib')

from honeybeex.radiance.material.plastic import PlasticMaterial
_name, _ref = IN[0], IN[1]
if _name and _ref is not None:
	OUT = PlasticMaterial.bySingleReflectValue(_name, _ref)
```

![image](https://cloud.githubusercontent.com/assets/2915573/21457527/06b7a934-c8fe-11e6-890d-6021d2a017d4.png)

**Comment by andrewkukla** [comment]
Hi @mostaphaRoudsari, I did as instructed and it worked.
Thank You!
