### ISSUE TITLE
Generate Test Points by Grid Size

### ISSUE THREAD

**Issue by schaggar16** [ladybug-analysis-tools/honeybee-plus#29]
i am using Revit 2016 / Dynamo 1.2 / Honeybee 0.0.8

With the sample .RVT file in the extras folder, i am trying to use the 'Honeybee Surface' node to generate the geometry - which works. 
However, when i look to use the 'Generate Test Points by Grid Size' node, i get the following error: 
ERROR:
	len() of unsized object
If you think this is a bug submit an issue on github.
https://github.com/ladybug-analysis-tools/honeybee-plus/issues
and include below error message:
Traceback (most recent call last):
File "<string>", line 26, in <module>
File "C:\Users\Test\AppData\Roaming\Dynamo\Dynamo Revit\1.2\packages\Honeybee\extra\honeybeex\geometryoperation.py", line 339, in __init__
assert len(self.surfaces) == len(self.borders), 
\
TypeError: len() of unsized object

This errors occurs when i connect the selected surface directly and via Honeybee Surface into the Node

**Comment by mostaphaRoudsari** [comment]
@schaggar16 can you share the geometry that you're using to generate the test points? Is it part of the sample model?

**Comment by schaggar16** [comment]
Hi, I am using the sample file. And using the select faces node to input into the honeybee surface node.

**Comment by schaggar16** [comment]
i have attached the revit file i am using.

**Comment by mostaphaRoudsari** [comment]
This is already answered here: https://github.com/ladybug-analysis-tools/honeybee-plus/issues/32#issuecomment-272874432
