### ISSUE TITLE
honeybee_grasshopper module object has no attribute hbsurface

### ISSUE THREAD

**Issue by antonszilasi** [ladybug-analysis-tools/honeybee-plus#30]
@mostaphaRoudsari 

This is an error that has been popping up some time to time and I'm scratching my head, I actually got it to work by restarting Rhino all together thereby re-setting all the modules in IronPython. Now however that doesn't seem to work even with your Honeybee installer.

![module object has no attribute](https://cloud.githubusercontent.com/assets/8773483/21525314/2354f7d0-cce2-11e6-9a9e-56ab59ccdff5.png)

![honeybee grasshopper](https://cloud.githubusercontent.com/assets/8773483/21525319/2794a87c-cce2-11e6-94b1-a74a3c17d0c8.JPG)

Clearly the module object does have an attribute hbsurface as can be seen from the installer package below:

![honeybee_grasshopper](https://cloud.githubusercontent.com/assets/8773483/21525385/97e6364a-cce2-11e6-9cb2-5cf00bb0adfb.JPG)

**Comment by mostaphaRoudsari** [comment]
@antonszilasi this is a known bug and and @DambronOlivier shared the current solution. It's an issue with how Grasshopper caches the libraries. will be fixed soon.

**Comment by mostaphaRoudsari** [comment]
This should be fixed now. Update the code and restart Rhino and Grasshopper and it should work fine afterwards!
