### ISSUE TITLE
Generate test points by gridsize runs w/o an input for _borders

### ISSUE THREAD

**Issue by andrewkukla** [ladybug-analysis-tools/honeybee-plus#32]
I have extracted surfaces form Revit conceptual model and created HB surfaces. 
Run Radiance says that they are not valid. Any idea why?

![image](https://cloud.githubusercontent.com/assets/24529228/21689509/7cbe4c0e-d368-11e6-9c51-cc42110b57d3.png)

**Comment by mostaphaRoudsari** [comment]
Hi @andrewkukla! Because the first item is a list. If you flatten the surfaces before connecting it to the node it should work fine. We can also add that as a check to the node.

**Comment by andrewkukla** [comment]
Hi @mostaphaRoudsari, Thanks for the quick reply.
Flattening indeed solves the problem with the HBsurfaces.
Now it seems I have an issue with my recipe. 
The error shows up when I connect it to Run Radiance Simulation node.
![image](https://cloud.githubusercontent.com/assets/24529228/21691624/44501c86-d371-11e6-8881-264bb8244ff8.png)

I have used "Generate test points" from LB because "Generate Test points by Grid Size" gives me "len() of unsized object" error.

![image](https://cloud.githubusercontent.com/assets/24529228/21691654/699b855c-d371-11e6-90c8-6ea2bb56de1e.png)

**Comment by mostaphaRoudsari** [comment]
Hi @andrewkukla, It's hard to day without checking your file. Can you share your file with me?

**Comment by andrewkukla** [comment]
Hi @mostaphaRoudsari, please find attached the .rvt and .dyn files.
[daylight DLF CI sky from conceptual mass 170105.zip](https://github.com/ladybug-analysis-tools/honeybee-plus/files/689471/daylight.DLF.CI.sky.from.conceptual.mass.170105.zip)
I really appreciate your help.
I saw in another post that  "len() of unsized object" is identified as a bug. 
Do you have a time-frame for the fix?

**Comment by schaggar16** [comment]
Hi @mostaphaRoudsari, i am also getting the same ToRadString() error when using HBSurface. I have attached my dynamo graph. I am looking to generate the geometry withing Dynamo rather than pull it from Revit. 
[HBSurface_Test.zip](https://github.com/ladybug-analysis-tools/honeybee-plus/files/704614/HBSurface_Test.zip)

**Comment by mostaphaRoudsari** [comment]
Hi @andrewkukla and @schaggar16 I will check this issue over the weekend and let you th results. Sorry for the delay.

**Comment by mostaphaRoudsari** [comment]
This error is happening because you haven't provided the _borders for the input testSurfaces. I should have not provided a null value as default for _borders as it is a required input. If you create the border of the surface as a polygon and connect it to the input it will work fine.

![image](https://cloud.githubusercontent.com/assets/2915573/21986573/f7d22c36-dbcd-11e6-815b-1ad7ccb19198.png)

I'll leave this open to make sure to remove the default value for the next release.

**Comment by schaggar16** [comment]
Thanks @mostaphaRoudsari. seems to have worked but i am now getting a new error within the Run Radiance simulation Node - it cannot find None/ocave.exe - i believe this maybe an issue with my Radiance install but would like to confirm with you first.

**Comment by schaggar16** [comment]
hi @mostaphaRoudsari , i have updated the dynamo file to include the the creation of the border. however, i am still getting a toRADString Error within the Run Radiance Simulation. Have attached the files.
I am looking to run the simulation on models where the rooms/spaces havent been created yet, hence the focus on getting the HBSurface method working.  
[HB toRADString Error.zip](https://github.com/ladybug-analysis-tools/honeybee-plus/files/729273/HB.toRADString.Error.zip)

**Comment by mostaphaRoudsari** [comment]
Hi @schaggar16! I'll have a new version of honeybee in a week or two which is using a modified and stable library. Can you wait a little bit and test the newer version? I can also check your current file if it's critical.

**Comment by schaggar16** [comment]
Thanks for getting back to me @mostaphaRoudsari, look forward to working with the new version. It is a bit time critical that i can get this dynamo graph to work - would be great if you could have a look at it when you get the chance. Much appreciated.

**Comment by mostaphaRoudsari** [comment]
@schaggar16 just pushed the new version (0.0.9) to the package manager that addresses both of these issues. Install the new version. Restart dynamo and your file should work fine.

**Comment by schaggar16** [comment]
@mostaphaRoudsari Worked a charm - thanks. I assume there is still to be another version to be released in 1-2 weeks?

**Comment by mostaphaRoudsari** [comment]
@schaggar16 yes. The new version supports annual analysis and more!
