### ISSUE TITLE
True/False to Write input of Run Radiance Analysis component

### ISSUE THREAD

**Issue by DambronOlivier** [ladybug-analysis-tools/honeybee-plus#34]
@mostaphaRoudsari 

When setting a new name for the subFolder and the write to True, we need to turn it to False and back to True again, before the folder is recognized properly.
![first time click write dcib](https://cloud.githubusercontent.com/assets/21184323/22061723/2fb82186-dd6e-11e6-84c2-cca6c3f55192.PNG)

![first time click write dcib2](https://cloud.githubusercontent.com/assets/21184323/22061774/6add89d6-dd6e-11e6-8eae-23c4d050ccea.PNG)

**Comment by mostaphaRoudsari** [comment]
@DambronOlivier can you restart Rhino and try this again. This should be fixed after the last night updates. I can't recreate the error. Also how do you update honeybee[+]? I wonder if the files are not updated correctly.

**Comment by DambronOlivier** [comment]
Yes indeed, it works now that I have restarted Rhino.
I had only unloaded and reloaded the Grasshopper plugin.

Thank you @mostaphaRoudsari
