### ISSUE TITLE
EPW to WEA for Daylight coefficient simulations

### ISSUE THREAD

**Issue by DambronOlivier** [ladybug-analysis-tools/honeybee-plus#35]
Hi @mostaphaRoudsari ,

I encountered this issue when using an epw file from Meteonorm.
![captureaa](https://cloud.githubusercontent.com/assets/21184323/22062551/3db9ae9a-dd72-11e6-9937-4a69e3652445.PNG)

In order to solve this I opened the epw and replaced the "LONDON/GATWICK" by "LONDON GATWICK".
Worked well. Perhaps others will encounter this as well.

![capturebb](https://cloud.githubusercontent.com/assets/21184323/22062632/9afbbb84-dd72-11e6-9f96-44c251eedde1.PNG)

**Comment by mostaphaRoudsari** [comment]
Thanks @DambronOlivier for reporting! This should also be fixed now.

**Comment by DambronOlivier** [comment]
Thank you @mostaphaRoudsari !
